### ISSUE TITLE
Cannot get rate limits for discord.com

### ISSUE THREAD

**Issue by kozabrada123** [polyphony-chat/chorus#113]
Trying to connect an Instance to discord.com's api yields the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"404: Not Found\", expected struct Message", line: 1, column: 28)', .../src/api/policies/instance/limits.rs:328:52
```

This happens because discord.com doesn't implement `/policies/instance/limits` (since that's a spacebar only endpoint :P)

It returns `{"message": "404: Not Found", "code": 0}` when chorus tries to deserialize the response into the Limits Config struct

```rust
pub struct Config {
        pub user: User,
        pub guild: Guild,
        pub message: Message,
        pub channel: Channel,
        pub rate: Rate,
        pub absoluteRate: AbsoluteRate,
}
```

`invalid type: string \"404: Not Found\", expected struct Message` comes from the `message` field being the same in the real response and the 404 response

## Sugestion how to fix this

Check if the GET limits requests returns a 404, if it does, fallback to a default (discord.com's default ratelimits)

**Comment by bitfl0wer** [comment]
yeah i really wanted to re-do the rate limiter anyways since it was once of the first things i did in rust, ever, and it kinda... sucks xD 

we could make it so that having the actual ratelimiting checker is an option which can be turned on and off

**Comment by kozabrada123** [comment]
I mean, you could add an option to disable it, but having build in rate limiting is good

**Comment by bitfl0wer** [comment]
Yeah definitely! I do not plan to remove it, just re-*do* it. :)
