### ISSUE TITLE
Use Result instead of Option<ChorusLibError>

### ISSUE THREAD

**Issue by SpecificProtagonist** [polyphony-chat/chorus#116]
Rust generally uses `Option::Some`/`Result::Ok` to indicate success and `Option::None`/`Result::Err` to indicate failure. Both implement the `Try` trait, allowing easier error management with `?`.

For functions that don't return a value on success Chorus does the opposite and returns `Some` on failure and `None` on success. This can be better represented via `Result<(), ChorusLibError>`. It's also convention to define a helpful type alias: `type Result<T> = std::result::Result<T, ChorusLibError>;`.

**Comment by bitfl0wer** [comment]
I have wondered if there isn't a better way to do this, when I wrote that ^^ Sounds reasonable!

**Comment by kozabrada123** [comment]
> For functions that don't return a value on success Chorus does the opposite and returns Some on failure and None on success. This can be better represented via Result<(), ChorusLibError>. It's also convention to define a helpful type alias: type Result<T> = std::result::Result<T, ChorusLibError>;.

Yeah, I remember calling a function and getting an error upon unwrapping because the function succeeded with no errors :P

**Comment by Vivlz** [comment]
I'll try and fix this!

**Comment by kozabrada123** [comment]
Merged in #119
