### ISSUE TITLE
Doc comment improvements

### ISSUE THREAD

**Issue by SpecificProtagonist** [polyphony-chat/chorus#129]
While types and names convey the most important information, often doc comments are helpful or necessary. The current ones still have some issues though:
- Many use `///`, but some use `/**`
- There has been some drift between comments and reality, such as in [`Channel::modify`](https://github.com/polyphony-chat/chorus/blob/40edc2c7feb7777cb75a6c84ce5fff4d20bda165/src/api/channels/channels.rs#LL58C7-L77C1)
- There's a lot of tautology: Often they just restate the types and names of the arguments & return value. For example:
  ```rust
    /// Edits the permission overwrites for a channel.
    ///
    /// # Arguments
    ///
    /// * `user` - A mutable reference to a [`UserMeta`] instance.
    /// * `channel_id` - A string slice representing the ID of the channel.
    /// * `overwrite` - A [`PermissionOverwrite`] instance representing the new permission overwrites.
    ///
    /// # Returns
    ///
    /// This function returns a result that is either [`Ok(())`] if the request is successful, or an [`Err(ChorusLibError)`].
    pub async fn edit_permissions(
        user: &mut UserMeta,
        channel_id: Snowflake,
        overwrite: PermissionOverwrite,
    ) -> ChorusResult<()> {…
  ```
  All of the information in the doc comment is a restatement of the types and names present. For that reason, function documentation in rust usually doesn't include an extra arguments section and instead refers to the arguments as needed when describing the function's behavior ([example](https://doc.rust-lang.org/nightly/src/core/option.rs.html#602)).  
- Some functions/structs could do with more descriptions about semantics.
- Ideally there would be doctests (executable examples) as well as a higher-level overview and more examples.

**Comment by bitfl0wer** [comment]
Note: `Instance::new()` is outdated when #144 gets merged.
