### ISSUE TITLE
Login auth test

### ISSUE THREAD

**Issue by SpecificProtagonist** [polyphony-chat/chorus#141]
There should be a test for login in. Related: There is an existing auth test for account registration, but the common test bundle setup functionality performs a registration beforehand anyways, so that test can probably be removed.

**Comment by bitfl0wer** [comment]
there is no login test because our user schema is more up to date than the one used on the spacebar server, which causes the test and, logically the CI to fail :P

**Comment by bitfl0wer** [comment]
the spacebar people should simply update their stuff :3 
(i hacve made a pr which has an issue but i havent worked on it since 3 months ago lol, so it kind of is my fault that it's like this)

**Comment by kozabrada123** [comment]
I believe this was added in 05fd02a
