### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by SpecificProtagonist** [polyphony-chat/chorus#142]
There are a lot of cases where chorus panics instead of handling errors, chief among them in `deserialize_response` when a request fails. This should not happen, encountering errors is expected.

Additionally, `ReceivedErrorCodeError` contains the http status code of the failed request, but discards the response body (at least the spacebar server returns useful information about why the request failed), making debugging harder.

Less important: The error handling code can be more succinctly expressed using idioms such as the try operator (`?`) or `.map_err` and friends. Also, since this crate is called chorus, not choruslib, the main error type should be called `ChorusError`, not `ChorusLibError`; and because it already contains "error", its variants don't need "error" as a suffix.

**Comment by bitfl0wer** [comment]
Will be fixed in the ratelimiter-rewrite branch.

**Comment by bitfl0wer** [comment]
Will be fixed in the RateLimiter-rewrite branch
