### ISSUE TITLE
Discord.com does not support bearer auth

### ISSUE THREAD

**Issue by kozabrada123** [polyphony-chat/chorus#181]
At the time of writing, chorus uses bearer authentication in its requests, which works for Spacebar servers.

On discord.com however, things are a little different:
`Authorization`: `<token>` works, and is used in the official client, while
`Authorization`: `Bearer <token>` doesn't work

If we want to have compatibility with discord.com, we'd need to switch from bearer auth to just setting the Authorization header to the token.

(Note that spacebar servers also support the discord.com way, so this shouldn't break anything)

**Comment by bitfl0wer** [comment]
This officially makes Discord dot com the Discord-implementation with the worst compatibility /j
