### ISSUE TITLE
Get User Burst Credits

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#219]

**Comment by kozabrada123** [comment]
Seems like this route was removed from userdoccers??

discord-userdoccers/discord-userdoccers@1085c4fba4234965b97ea73badb7f3a37f14f9ea

**Comment by kozabrada123** [comment]
It seems to still exist however, so I implemented it anyway

**Comment by kozabrada123** [comment]
Added in #537
