### ISSUE TITLE
Multithreading and Gateways

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#22]
The foundation for Gateways has been made! The library now allows you to write code which immediately runs, when a specific event is received via the gateway.

However: Actually communicating with the gateway and receiving those events is where I have failed until now. I just couldn't get it to work the way I would have liked to, and I require help on this one. 

From my POV, an ideal implementation would have each Gateway/Websocket running in a seperate thread. Each gateway thread updates the `GatewayEvent`s (defined in src/gateway.rs), which would trigger the observers.

**Comment by kozabrada123** [comment]
(Should've said this earlier)
I'm working on this and it's sorta done, once I test everything and make sure its fully working I'll open a pr
