### ISSUE TITLE
Save and Load RateLimits to disk

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#34]
A feature should be added that allows RateLimits to be written to disk as `.json`, `.yml` or another format such as `.kdl`. This would allow RateLimit information to persist, which would make it harder to run into rate limits by accident.

**Comment by bitfl0wer** [comment]
Fair point! Another case of the simplest solution being the best haha

**Comment by TheArcaneBrony** [comment]
i dont think storing ratelimits on disk would be a good idea?

**Comment by bitfl0wer** [comment]
Elaborate? Storing the ratelimits is important if you want to accurately keep track of what your current rate limits are. If you restart the library/application and you do not have them saved anywhere, then it'll just reset to the normal, unchanged ratelimits, and you'd run into limits

**Comment by TheArcaneBrony** [comment]
which is fine, how are you gonna handle different ratelimit implementations?

**Comment by bitfl0wer** [comment]
If you are referring to the GlobalRegister and GlobalMessage limits: We don't track those. We cannot even track those, AFAIK.
