### ISSUE TITLE
Implement Gateway Functionality

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#4]
There needs to be a working implementation of a gateway, which connects to the Gateway of an instance and can send and receive messages. It would be great if the Gateway would emit 'events' on things like message received, message edited message deleted etc. These events could then, for example, be used by the client to update its UI when the event happens.

**Comment by Stilic** [comment]
maybe i could do that (i need to learn rust tho)

**Comment by bitfl0wer** [comment]
> maybe i could do that (i need to learn rust tho)

Feel free to go ahead, but this doesn't sound concrete enough yet for me to change the Issues' status from "Available" to "In Progress". If there's any news/you've made progress, feel free to update here!

**Comment by bitfl0wer** [comment]
Claiming this :)

**Comment by bitfl0wer** [comment]
Outlining what the implementation should look like:
- Each Gateway object should ideally be running in its' own thread.
- It should automatically parse things like Message or Guild Events and forward the parsed message to subscribers
- Cache as little as possible; information should only be retrieved and be made ready-for-use, not stored. Consumption of this information should be handled by client implementations. Any given Event should only have one information entity assigned to it.

**Comment by bitfl0wer** [comment]
hang on this aint finished yet
