### ISSUE TITLE
2-Factor-Authentication

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#40]
2-Factor-Authentication functionality should be checked for functionality.

**Comment by kozabrada123** [comment]
MFA (Multi factor verification) is a pretty important part of the API, some sensitive routes require it.

[relevant documentation](https://docs.discord.sex/authentication#mfa-verification)

**Comment by xystrive** [comment]
Working on this feature.

**Comment by kozabrada123** [comment]
I'll pick this back up again, this is a very useful feature and it is 90% finished

**Comment by xystrive** [comment]
> I'll pick this back up again, this is a very useful feature and it is 90% finished

@kozabrada123 I have been busy lately, not entirely sure when I am available to make contributions to the project again.
I hope the project is going well, I am glad my contributions have had some meaning.

**Comment by kozabrada123** [comment]
Added in 0.18.0
