### ISSUE TITLE
User profile customization

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#41]
It should be possible to modify all aspects of a user profile using this library. This includes, but is not limited to:

- [x] Username
- [x] Discriminator
- [x] Avatar
- [x] Accent Color
- [x] Email
- [x] Pronouns
- [x] Banner
- [x] Bio
- [ ] Theme Colors
- [ ] Phone
- [x] NSFW
- [x] Disabled
- [ ] Deletion
- [ ] Testing

**Comment by bitfl0wer** [comment]
https://docs.spacebar.chat/routes/#patch-/users/-id-/profile/ Has to be implemented for pronouns and other stuff

**Comment by kozabrada123** [comment]
For changing phone numbers:
- DELETE /api/v9/users/@me/phone
`{"password":"userpassword","change_phone_reason":"user_settings_update"}`
Which also requires MFA

- POST https://discord.com/api/v9/users/@me/phone
`{"phone":"+123456789","change_phone_reason":"user_settings_update"}`

- POST https://discord.com/api/v9/phone-verifications/verify once your receive the code
`{"phone":"+123456789","code":"123455"}`, which returns `{"token":"eyJpZCI6NDYzNjQwMzkxMTk2MDgyMTc4LCJwaG9uZSI6IisxMjM0NTY3ODkifQ==.ZvzUJg.6_5e-y_lytG2_KIeBcRxNVy2WlE"}`

Then you need to solve a captcha and provide your password
- POST https://discord.com/api/v9/users/@me/phone
`{"phone_token":"eyJpZCI6NDYzNjQwMzkxMTk2MDgyMTc4LCJwaG9uZSI6IisxMjM0NTY3ODkifQ==.ZvzUJg.6_5e-y_lytG2_KIeBcRxNVy2WlE","password":"youruserpassword","change_phone_reason":"user_settings_update"}`
