### ISSUE TITLE
Changing the license of chorus

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#470]
@kozabrada123 @SpecificProtagonist @Zert3x @striezel @Vivlz @skyrina 

The project, and thus your contributions as well, are currently distributed under the GNU Affero General Public License v3.0 (AGPL-3.0). When I created the chorus repository about half a year ago, I was honestly not quite aware of what the AGPL-3.0 would imply for this project, and thought it was a good fit for chorus. Since then, the project has grown a lot, and there have been a bunch of new contributors and changes to scope.

I am concerned that the requirement to force everyone, who wants to use chorus for their own project, to license their entire project under the AGPL-3.0 as well, is overly stringent and will likely most likely hinder the software's broader use and adoption. 

Therefore, I am considering a change to the Mozilla Public License v2.0 (MPL 2.0), a weak-copyleft license that also supports the freedom to use, study, share, and modify the software, while only requiring modifications to MPL licensed code to be released. (A)GPL affects other code linked to GPL licensed files as well. This assures that chorus and its' forks and modifications will always stay open source, while allowing other parts of software using chorus to be licensed under different terms (this is called "file-level copyleft").

However, I cannot make this change without the explicit consent of all people who have contributed to chorus in the past.

If you agree with this change, please reply to this message, explicitly indicating your agreement by writing, "I agree to re-licensing of all my past contributions to the chorus repository from the AGPL-3.0 license to the Mozilla Public License v2.0."

If you do not agree to the license change or if you have any questions or concerns regarding this matter, please absolutely let me know. Your thoughts, feelings, and preferences carry significant weight in this decision. 

You can also contact me privately via e-mail at [flori@polyphony.chat](mailto:flori@polyphony.chat) (OpenPGP [supported](https://keys.openpgp.org/search?q=flori%40polyphony.chat)) if you have concerns or opinions you would rather voice in private.

**Comment by skyrina** [comment]
im not sure if i contributed towards this repo yet but I agree to the re-licensing of all my past contributions to the chorus repository from AGPL-3.0 to Mozilla Public License v2.0.

**Comment by Vivlz** [comment]
In total I wrote like 2 lines but sure, I agree to re-licensing of all my past contributions to the chorus repository from the AGPL-3.0 license to the Mozilla Public License v2.0.

**Comment by not-ivy** [comment]
![49b740aea116ec3807d6e620491d8f63 (1) @EmeraldSnorlax](https://github.com/polyphony-chat/chorus/assets/47074495/b2a8bb07-ee83-4c74-afd8-99da923f473d)

**Comment by kozabrada123** [comment]
I agree to re-licensing all my contributions to chorus to the MPL 2.0

**Comment by kozabrada123** [comment]
I was curious so I did a bit of research, if anyone is interested: https://users.rust-lang.org/t/licensing-mit-apache-2-vs-mpl-2-0/46250

**Comment by kozabrada123** [comment]
No idea if this is real, but:
> So why did Rust go with MIT OR APACHE-2.0 rather than MPL-2.0? If I properly recall seeing one the people who were around early (graydon, even?) saying it, it's because MPL-2.0 didn't exist when Rust first started development, and was licensed under MIT OR APACHE-2.0, and if it had, it likely might have been licensed under the one license rather than the OR it is today.

**Comment by striezel** [comment]
> No idea if this is real, but:
> 
> > So why did Rust go with MIT OR APACHE-2.0 rather than MPL-2.0? If I properly recall seeing one the people who were around early (graydon, even?) saying it, it's because MPL-2.0 didn't exist when Rust first started development, and was licensed under MIT OR APACHE-2.0, and if it had, it likely might have been licensed under the one license rather than the OR it is today.

For what it's worth, the Mozilla Public License 2.0 was released [in 2011](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2011-August/001294.html), and depending on where you start counting, Rust started somewhere between [2006](https://www.technologyreview.com/2023/02/14/1067869/rust-worlds-fastest-growing-programming-language/) and [early 2012](https://doc.rust-lang.org/nightly/releases.html#version-01--2012-01-20) (Rust version 0.1). So initially MPL 2.0 was not available, but earlier versions of MPL were.

**Comment by striezel** [comment]
As for the license change, I am basically fine with any weaker copyleft license than AGPL, be it GNU General Public License version 2 or 3, GNU Lesser General Public License version 2.1 or 3, or Mozilla Public License 2.0.

I agree to re-licensing of all my past contributions to the chorus repository from the AGPL-3.0 license to the Mozilla Public License v2.0.

**Comment by Zert3x** [comment]
I agree to the relicensing, this seems like a step in the right direction for the project

**Comment by bitfl0wer** [comment]
As everyone who has commited so far has agreed to the license change, I will mark this issue as closed now and merge the license changes. Thank you, everyone! :)
