### ISSUE TITLE
Custom message routing

### ISSUE THREAD

**Issue by erkinalp** [polyphony-chat/chorus#481]
Required feature for IoT and serious business use cases, to allow different views of channels to different users, without actually copying messages in the database.

**Comment by bitfl0wer** [comment]
Polyphony (Chat) and chorus are not intended for IoT/enterprise-grade use cases. The only software developed by this organization with enterprise specifically in mind is polyproto.

**Comment by kozabrada123** [comment]
Why is this is issue on the client crate repo?

**Comment by erkinalp** [comment]
@kozabrada123 because you need sth to define and manage those routes in the client side too, in order to be able to utilise such functionality without directly poking into the database of your server

**Comment by kozabrada123** [comment]
> because you need sth to define and manage those routes in the client side too

maybe those routes should be defined on the server side first? once there's a functioning server implementation then we'll look into supporting it in the client
