### ISSUE TITLE
Re-evaluate `ChorusUser::shell`

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#494]
https://github.com/polyphony-chat/chorus/blob/ca9c4b8949c021822b7ff974c15d5d3575b53c15/src/instance.rs#L208-L232

Re-evaluate if ChorusUser::shell is still needed, and if so, if it is implemented correctly.
I remember that this method was used as a sort of "hack" a couple months ago, but the code has changed
a lot since then, so it might not be needed anymore.

**Comment by kozabrada123** [comment]
It is actually still used in several places:

https://github.com/polyphony-chat/chorus/blob/ca9c4b8949c021822b7ff974c15d5d3575b53c15/src/api/auth/login.rs#L17-L34

https://github.com/polyphony-chat/chorus/blob/ca9c4b8949c021822b7ff974c15d5d3575b53c15/src/api/auth/register.rs#L21-L41

https://github.com/polyphony-chat/chorus/blob/ca9c4b8949c021822b7ff974c15d5d3575b53c15/src/api/users/users.rs#L152-L161

(This one should likely at least support a version with an existing user)

https://github.com/polyphony-chat/chorus/blob/ca9c4b8949c021822b7ff974c15d5d3575b53c15/src/api/users/users.rs#L117-L130

**Comment by kozabrada123** [comment]
Also, note that despite ChorusUser including a gateway object

https://github.com/polyphony-chat/chorus/blob/ca9c4b8949c021822b7ff974c15d5d3575b53c15/src/instance.rs#L208-L218

 login and register spawn a new gateway, which should probably be fixed :P

https://github.com/polyphony-chat/chorus/blob/ca9c4b8949c021822b7ff974c15d5d3575b53c15/src/api/auth/login.rs#L21-L45

https://github.com/polyphony-chat/chorus/blob/ca9c4b8949c021822b7ff974c15d5d3575b53c15/src/api/auth/register.rs#L25-L54

**Comment by bitfl0wer** [comment]
I sort of have an issue with the ::shell function even needing to exist in the first place, seems like an architectural blunder from my side. But maybe it's also fine and I am reading too much into this 🥲

**Comment by kozabrada123** [comment]
If possible, I think it's better not to have sth like this is the first place, though I don't have that much of an issue with using it

**Comment by kozabrada123** [comment]
either way functions like register and login should probably expand the created shell, instead of using it for one request and then building a new user

**Comment by kozabrada123** [comment]
Oh dear, I just found this:

login:
- creates shell 1
    - creates gateway 1
- calls `get_user()`
    - creates shell 2
        - creates gateway 2
 - creates gateway 3

register:
- creates shell 1
    - creates gateway 1
- calls `get_user()`
    - creates shell 2
        - creates gateway 2
- calls `get_settings()`
    - creates shell 3
        - creates gateway 3
- creates gateway 4

**Comment by bitfl0wer** [comment]
Oh dear lord

what have I done

**Comment by bitfl0wer** [comment]
To be fair, it's ugly, but it works, and it's not like this has affected the rest of the software architecture or performance in any significant way, so it's "okay"

**Comment by kozabrada123** [comment]
Sure, but I'd still rather fix it

**Comment by bitfl0wer** [comment]
Absolutely! Hence the issue

**Comment by kozabrada123** [comment]
I think the way we use shell is now is pretty alright, I don't we need to change the method itself
