### ISSUE TITLE
Types change causes build error in Symfonia

### ISSUE THREAD

**Issue by kozabrada123** [polyphony-chat/chorus#523]
I'm guilty of this of course, just opening it up to an issue to track it better

Pr #514 causes a build error in Symfonia by changing `pub theme_colors: Option<Vec<u8>>,` to `pub theme_colors: Option<Vec<u32>>,`, since `Vec<u8>` can be encoded by Sqlx but `Vec<u32>` cannot.

An ideal solution to this would bring include a new type for theme colors, with a custom Sqlx encoding implementation. Note that the most accurate representation of theme colors is likely `(u32, u32)` or `[u32; 2]`

**Comment by kozabrada123** [comment]
Atm this issue prevents Symfonia from updating chorus past commit d591616

**Comment by bitfl0wer** [comment]
Fixed by #533
