### ISSUE TITLE
Get User Recent Games

### ISSUE THREAD

**Issue by kozabrada123** [polyphony-chat/chorus#538]
https://docs.discord.sex/resources/user#get-user-recent-games

Part of #189

**Comment by bitfl0wer** [comment]
Is this a v10 endpoint, or still part of v9?

**Comment by kozabrada123** [comment]
This is.. interesting

both `/api/v9/users/{id}/profile/recent-games` and `/api/v10/users/{id}/profile/recent-games` return a 404, meanwhile `/api/v9/users/{id}/profile` and `/api/v10/users/{id}/profile` work with no other changes other than the url

**Comment by kozabrada123** [comment]
It is true that the profile I was testing on had no recent games, but I'd expect it to return an empty array instead of a 404
