### ISSUE TITLE
Add system for differentiation of instance softwares

### ISSUE THREAD

**Issue by kozabrada123** [polyphony-chat/chorus#557]
Add a system to let `chorus` itself and library users know which server software an instance is running, and adjust logic accordingly.

Possible usecases:
- routes which are implemented differently in different softwares
- schemas and types which are different in different softwares
- features some implementations may support, while others don't
- using the right `GatewayOptions`

**Comment by bitfl0wer** [comment]
Spacebar officially recommends using the `.well-known/spacebar` endpoint to resolve the URL of the API server. A similar thing could be done for symfonia using `well-known/symfonia` perhaps?

**Comment by kozabrada123** [comment]
Some potential options for server softwares:
- `Symfonia`
- `Spacebar`
- `GenericSpacebarCompatible`

with some methods like `supports_gateway_etf`, `supports_gateway_zlib`, `recommended_gateway_options`, `supports_pomelo`, ...

**Comment by kozabrada123** [comment]
See https://github.com/polyphony-chat/chorus/tree/instance-softwares

**Comment by kozabrada123** [comment]
The holy grail for this would be https://github.com/spacebarchat/server/issues/1222

**Comment by kozabrada123** [comment]
and the equivalent for symfonia: https://github.com/polyphony-chat/symfonia/issues/49

**Comment by kozabrada123** [comment]
Completed in #560
